export interface ErrorResponseErrorProps {
  statusCode: number;
  error: string;
  message: Datum[];
  data: Datum[];
}

export interface Datum {
  messages: Message[];
}

export interface Message {
  id: string;
  message: string;
}

export interface LoginResponseProps {
  jwt: string;
  user: UserInfoProps;
}

export interface UserInfoProps {
  id: number;
  blocked: boolean;
  company: string;
  confirmed: boolean;
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
}

export interface CreateConferencieProps {
  time: string;
  url?: string;
  comments?: string;
  users_permissions_user: string;
}

// Generated by https://quicktype.io

export interface ResumeResponseProps {
  avatar: Avatar;
}

export interface Avatar {
  name: string;
  formats: FormatsProps;
}

export interface FormatsProps {
  thumbnail: ImageProps;
  sm: ImageProps;
  md: ImageProps;
  lg: ImageProps;
  xl: ImageProps;
  "2xl": ImageProps;
}

export interface ImageProps {
  hash: string;
  ext: string;
  width: number;
  height: number;
}

export type KeysFormats = "thumbnail" | "sm" | "md" | "lg" | "xl" | "2xl";
